//! SeaORM Entity. Generated by sea-orm-codegen 0.3.1

pub use super::addresses::Entity as Addresses;
pub use super::authentication::Entity as Authentication;
pub use super::employees::Entity as Employees;
