//! SeaORM Entity. Generated by sea-orm-codegen 0.3.0

pub use super::addresses::Entity as Addresses;
pub use super::authentication::Entity as Authentication;
pub use super::employees::Entity as Employees;
pub use super::roles::Entity as Roles;
pub use super::sessions::Entity as Sessions;
pub use super::telephone_numbers::Entity as TelephoneNumbers;
